name: integracion continua con node.js

on: 
  pull_request:
    branches: [ master ]

jobs: 
  ci_to-master:
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setuo-node@v1
        - run: npm ci
        - run: npm test
        - run: npm run build


